spring:
  application:
    name: insurance-configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JEscGon/insurance-configserver
          default-label: main
          search-paths:
            - config
          clone-on-start: true

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.springframework.cloud.config.server: DEBUG
    org.eclipse.jgit: INFO